const products = window.HARVEST_PRODUCTS || [];
const productId = window.HARVEST_PRODUCT_ID || new URLSearchParams(window.location.search).get("product");
const product = products.find((item) => item.id === productId);
let selectedVariantId = product?.variants?.find((variant) => variant.quantity === product.quantity)?.id || product?.variants?.[0]?.id;
const CART_STORAGE_KEY = "harvest-treats-bag";
const MAX_ITEM_QUANTITY = 10;
let cart = restoreCart();
const page = document.querySelector("#productPage");
const cartPanel = document.querySelector("#cartPanel");
const cartCount = document.querySelector("#cartCount");
const cartItems = document.querySelector("#cartItems");
const cartTotal = document.querySelector("#cartTotal");
const formatPrice = (price) => `Rs. ${price.toLocaleString("en-IN")}`;

document.querySelector(".brand")?.setAttribute("href", "/");

function activeVariant() { return product?.variants?.find((variant) => variant.id === selectedVariantId); }
function renderVariantPicker() { const variant = activeVariant(); const packLine = Array.from(document.querySelectorAll(".product-info > p")).find((element) => element.textContent.includes("Pack size:")); const priceLine = document.querySelector(".detail-price"); if (!variant || !packLine || !priceLine) return; packLine.innerHTML = `<label for="packSelect"><strong>Pack size:</strong></label> <select id="packSelect" class="pack-select">${product.variants.map((item) => `<option value="${item.id}" ${item.id === selectedVariantId ? "selected" : ""}>${item.quantity}</option>`).join("")}</select>`; priceLine.innerHTML = `<strong>${formatPrice(variant.sellingPrice)}</strong><del>${formatPrice(variant.mrp)}</del><span class="discount-label">${Math.round((1 - variant.sellingPrice / variant.mrp) * 100)}% OFF</span>`; document.querySelector("#packSelect").addEventListener("change", (event) => { selectedVariantId = event.target.value; renderVariantPicker(); }); }
function renderGallery() { const media = product?.gallery || []; const host = document.querySelector(".product-image"); if (!media.length || !host) return; const gallery = document.createElement("section"); gallery.className = "product-gallery"; gallery.setAttribute("aria-label", `${product.name} photos and videos`); gallery.innerHTML = `<p>More from this product</p>${media.map((item) => item.type === "video" ? `<video controls muted playsinline preload="metadata" aria-label="${item.label}"><source src="${item.src}" type="video/mp4">Your browser does not support video playback.</video>` : `<img src="${item.src}" alt="${item.alt}" loading="lazy">`).join("")}`; host.append(gallery); }

function restoreCart() { try { const saved = JSON.parse(localStorage.getItem(CART_STORAGE_KEY)); return Array.isArray(saved) ? saved.filter((line) => products.some((item) => item.id === line.id) && Number.isInteger(line.qty) && line.qty > 0) : []; } catch { return []; } }
function saveCart() { localStorage.setItem(CART_STORAGE_KEY, JSON.stringify(cart)); }
function openCart() { cartPanel.classList.add("open"); cartPanel.setAttribute("aria-hidden", "false"); }
function renderCart() { const totalQty = cart.reduce((sum, line) => sum + line.qty, 0); const total = cart.reduce((sum, line) => sum + (line.unitPrice || products.find((item) => item.id === line.id).discountedPrice) * line.qty, 0); cartCount.textContent = totalQty; cartTotal.textContent = formatPrice(total); cartItems.innerHTML = cart.length ? cart.map((line) => { const item = products.find((entry) => entry.id === line.id); const quantity = line.quantityLabel || item.quantity; const price = line.unitPrice || item.discountedPrice; return `<div class="cart-line"><div><p><strong>${item.name}</strong></p><small>${quantity} × ${line.qty} — ${formatPrice(price)} each</small></div><div class="cart-line-actions"><div class="quantity-control"><button type="button" data-change="-1" data-id="${item.id}" aria-label="Decrease quantity">−</button><span>${line.qty}</span><button type="button" data-change="1" data-id="${item.id}" aria-label="Increase quantity">+</button></div><button type="button" data-remove="${item.id}">Remove</button></div></div>`; }).join("") : "<p>Your bag is waiting for something good.</p>"; }
function addToCart() { const variant = activeVariant(); const line = cart.find((item) => item.id === product.id); if (line) { line.qty = Math.min(MAX_ITEM_QUANTITY, line.qty + 1); line.variantId = variant.id; line.quantityLabel = variant.quantity; line.unitPrice = variant.sellingPrice; line.mrp = variant.mrp; } else cart.push({ id:product.id, qty:1, variantId:variant.id, quantityLabel:variant.quantity, unitPrice:variant.sellingPrice, mrp:variant.mrp }); saveCart(); renderCart(); renderDetailActions(); }
function renderDetailActions() { const actions = document.querySelector(".detail-actions"); if (!actions || !product) return; const quantity = cart.find((item) => item.id === product.id)?.qty || 0; actions.classList.toggle("has-quantity", Boolean(quantity)); actions.innerHTML = `${quantity ? `<div class="quantity-control product-quantity-control detail-quantity-control" aria-label="Quantity for ${product.name}"><button type="button" data-detail-change="-1" aria-label="Decrease quantity">−</button><span aria-live="polite">${quantity}</span><button type="button" data-detail-change="1" aria-label="Increase quantity" ${quantity >= MAX_ITEM_QUANTITY ? "disabled" : ""}>+</button></div>` : `<button class="add-detail" type="button" data-detail-add>Add to cart</button>`}<button class="bag-detail" type="button" data-go-bag-detail>Go to bag</button>`; }
function renderProduct() { if (!product) { page.innerHTML = `<section class="not-found"><h1>Product not found</h1><p>That product page is unavailable. Browse the current Harvest Treats collection instead.</p><a class="primary-button" href="index.html#products">Shop all products</a></section>`; return; } document.title = `${product.name} | Harvest Treats`; document.querySelector('meta[name="description"]').content = `${product.description} Product details, nutrition and order options from Harvest Treats.`; page.innerHTML = `<section class="product-page"><nav class="breadcrumb" aria-label="Breadcrumb"><a href="index.html">Home</a><span>/</span><a href="index.html#products">Products</a><span>/</span><span>${product.name}</span></nav><div class="product-layout"><div class="product-image"><img src="${product.image}" alt="${product.name} ${product.quantity} pack"></div><div class="product-info"><p class="eyebrow">Harvest Treats • ${product.category}</p><h1>${product.name}</h1><p class="product-description">${product.description}</p><div class="detail-price"><strong>${formatPrice(product.discountedPrice)}</strong><del>${formatPrice(product.price)}</del><span class="discount-label">${product.discount}% OFF</span></div><p><strong>Pack size:</strong> ${product.quantity}</p><div class="detail-actions"><button class="add-detail" type="button" id="addToCart">Add to cart</button><button class="bag-detail" type="button" id="goToBag">Go to bag</button></div><p class="purchase-note">Listed price includes the displayed offer. Maximum 10 units of a product per bag.</p><div class="assurance-grid"><article class="assurance-card"><strong>Assured delivery</strong><p>Order support and delivery details are confirmed with you before fulfilment.</p></article><article class="assurance-card"><strong>Quality assured</strong><p>Thoughtfully sourced and packed for freshness. Check the sealed pack and label on delivery.</p></article></div><section class="detail-section"><h2>Product details</h2><p><strong>Ingredients:</strong> ${product.ingredients}</p><p><strong>How to enjoy:</strong> ${product.uses}</p></section><section class="detail-section"><h2>Nutrition information</h2><p class="nutrition-note">Approximate nutrition values per 100g. Please refer to the product label for the final nutrition declaration.</p><div class="nutrition-grid">${product.nutrition.map((value) => `<div>${value}</div>`).join("")}</div></section></div></div></section>`; document.querySelector("#addToCart").addEventListener("click", addToCart); document.querySelector("#goToBag").addEventListener("click", openCart); }
document.querySelector("#cartButton").addEventListener("click", openCart); document.querySelector("#closeCart").addEventListener("click", () => { cartPanel.classList.remove("open"); cartPanel.setAttribute("aria-hidden", "true"); });
cartItems.addEventListener("click", (event) => { const remove = event.target.closest("[data-remove]"); const change = event.target.closest("[data-change]"); if (remove) cart = cart.filter((line) => line.id !== remove.dataset.remove); if (change) { const line = cart.find((item) => item.id === change.dataset.id); line.qty = Math.max(0, Math.min(MAX_ITEM_QUANTITY, line.qty + Number(change.dataset.change))); cart = cart.filter((item) => item.qty); } saveCart(); renderCart(); });
page.addEventListener("click", (event) => { const add = event.target.closest("[data-detail-add]"); const change = event.target.closest("[data-detail-change]"); const bag = event.target.closest("[data-go-bag-detail]"); if (add) addToCart(); if (change) { const line = cart.find((item) => item.id === product.id); line.qty = Math.max(0, Math.min(MAX_ITEM_QUANTITY, line.qty + Number(change.dataset.detailChange))); cart = cart.filter((item) => item.qty); saveCart(); renderCart(); renderDetailActions(); } if (bag) openCart(); });
document.querySelector("#orderButton").addEventListener("click", () => { if (!cart.length) return; const lines = cart.map((line) => { const item = products.find((entry) => entry.id === line.id); return `${line.qty} x ${item.name} (${item.quantity}) - ${formatPrice(item.discountedPrice)} each`; }); window.open(`https://wa.me/919123068708?text=${encodeURIComponent(`Harvest Treats Order List:\n${lines.join("\n")}`)}`, "_blank", "noopener,noreferrer"); });
renderProduct(); renderVariantPicker(); renderGallery(); renderCart(); renderDetailActions();
