const products = window.HARVEST_PRODUCTS || [];
const productId = new URLSearchParams(window.location.search).get("product");
const product = products.find((item) => item.id === productId);
const CART_STORAGE_KEY = "harvest-treats-bag";
const MAX_ITEM_QUANTITY = 10;
let cart = restoreCart();
const page = document.querySelector("#productPage");
const cartPanel = document.querySelector("#cartPanel");
const cartCount = document.querySelector("#cartCount");
const cartItems = document.querySelector("#cartItems");
const cartTotal = document.querySelector("#cartTotal");
const formatPrice = (price) => `Rs. ${price.toLocaleString("en-IN")}`;

function restoreCart() { try { const saved = JSON.parse(localStorage.getItem(CART_STORAGE_KEY)); return Array.isArray(saved) ? saved.filter((line) => products.some((item) => item.id === line.id) && Number.isInteger(line.qty) && line.qty > 0) : []; } catch { return []; } }
function saveCart() { localStorage.setItem(CART_STORAGE_KEY, JSON.stringify(cart)); }
function openCart() { cartPanel.classList.add("open"); cartPanel.setAttribute("aria-hidden", "false"); }
function renderCart() { const totalQty = cart.reduce((sum, line) => sum + line.qty, 0); const total = cart.reduce((sum, line) => sum + products.find((item) => item.id === line.id).discountedPrice * line.qty, 0); cartCount.textContent = totalQty; cartTotal.textContent = formatPrice(total); cartItems.innerHTML = cart.length ? cart.map((line) => { const item = products.find((entry) => entry.id === line.id); return `<div class="cart-line"><div><p><strong>${item.name}</strong></p><small>${item.quantity} × ${line.qty} — ${formatPrice(item.discountedPrice)} each</small></div><div class="cart-line-actions"><div class="quantity-control"><button type="button" data-change="-1" data-id="${item.id}" aria-label="Decrease quantity">−</button><span>${line.qty}</span><button type="button" data-change="1" data-id="${item.id}" aria-label="Increase quantity">+</button></div><button type="button" data-remove="${item.id}">Remove</button></div></div>`; }).join("") : "<p>Your bag is waiting for something good.</p>"; }
function addToCart() { const line = cart.find((item) => item.id === product.id); if (line) line.qty = Math.min(MAX_ITEM_QUANTITY, line.qty + 1); else cart.push({ id:product.id, qty:1 }); saveCart(); renderCart(); }
function renderProduct() { if (!product) { page.innerHTML = `<section class="not-found"><h1>Product not found</h1><p>That product page is unavailable. Browse the current Harvest Treats collection instead.</p><a class="primary-button" href="index.html#products">Shop all products</a></section>`; return; } document.title = `${product.name} | Harvest Treats`; document.querySelector('meta[name="description"]').content = `${product.description} Product details, nutrition and order options from Harvest Treats.`; page.innerHTML = `<section class="product-page"><nav class="breadcrumb" aria-label="Breadcrumb"><a href="index.html">Home</a><span>/</span><a href="index.html#products">Products</a><span>/</span><span>${product.name}</span></nav><div class="product-layout"><div class="product-image"><img src="${product.image}" alt="${product.name} ${product.quantity} pack"></div><div class="product-info"><p class="eyebrow">Harvest Treats • ${product.category}</p><h1>${product.name}</h1><p class="product-description">${product.description}</p><div class="detail-price"><strong>${formatPrice(product.discountedPrice)}</strong><del>${formatPrice(product.price)}</del><span class="discount-label">${product.discount}% OFF</span></div><p><strong>Pack size:</strong> ${product.quantity}</p><div class="detail-actions"><button class="add-detail" type="button" id="addToCart">Add to cart</button><button class="bag-detail" type="button" id="goToBag">Go to bag</button></div><p class="purchase-note">Listed price includes the displayed offer. Maximum 10 units of a product per bag.</p><div class="assurance-grid"><article class="assurance-card"><strong>Assured delivery</strong><p>Order support and delivery details are confirmed with you before fulfilment.</p></article><article class="assurance-card"><strong>Quality assured</strong><p>Thoughtfully sourced and packed for freshness. Check the sealed pack and label on delivery.</p></article></div><section class="detail-section"><h2>Product details</h2><p><strong>Ingredients:</strong> ${product.ingredients}</p><p><strong>How to enjoy:</strong> ${product.uses}</p></section><section class="detail-section"><h2>Nutrition information</h2><p class="nutrition-note">Approximate nutrition values per 100g. Please refer to the product label for the final nutrition declaration.</p><div class="nutrition-grid">${product.nutrition.map((value) => `<div>${value}</div>`).join("")}</div></section></div></div></section>`; document.querySelector("#addToCart").addEventListener("click", addToCart); document.querySelector("#goToBag").addEventListener("click", openCart); }
document.querySelector("#cartButton").addEventListener("click", openCart); document.querySelector("#closeCart").addEventListener("click", () => { cartPanel.classList.remove("open"); cartPanel.setAttribute("aria-hidden", "true"); });
cartItems.addEventListener("click", (event) => { const remove = event.target.closest("[data-remove]"); const change = event.target.closest("[data-change]"); if (remove) cart = cart.filter((line) => line.id !== remove.dataset.remove); if (change) { const line = cart.find((item) => item.id === change.dataset.id); line.qty = Math.max(0, Math.min(MAX_ITEM_QUANTITY, line.qty + Number(change.dataset.change))); cart = cart.filter((item) => item.qty); } saveCart(); renderCart(); });
document.querySelector("#orderButton").addEventListener("click", () => { if (!cart.length) return; const lines = cart.map((line) => { const item = products.find((entry) => entry.id === line.id); return `${line.qty} x ${item.name} (${item.quantity}) - ${formatPrice(item.discountedPrice)} each`; }); window.open(`https://wa.me/919123068708?text=${encodeURIComponent(`Harvest Treats Order List:\n${lines.join("\n")}`)}`, "_blank", "noopener,noreferrer"); });
renderProduct(); renderCart();
