window.HARVEST_PRODUCTS = [
  { id:"premium-makhana", name:"Premium Makhana / Fox Nut", image:"Images/Premium_Makhana.jpeg", quantity:"200g", price:350, discount:20, discountedPrice:280, category:"Makhana", description:"Light, crunchy premium makhana, also known as fox nut, for a satisfying everyday snack.", ingredients:"Makhana (fox nuts).", nutrition:["Energy 347 kcal","Protein 9.7g","Carbohydrate 77g","Total fat 0.1g"], uses:"Enjoy roasted as a light snack, or add to trail mixes and everyday pantry recipes." },
  { id:"americano-almond", name:"Americano Almond", image:"Images/Americano_Almonds.jpeg", quantity:"200g", price:300, discount:20, discountedPrice:240, category:"Dry Fruits & Nuts", description:"Crunchy Americano almonds for snack bowls, breakfasts, desserts and daily pantry refills.", ingredients:"Almonds.", nutrition:["Energy 579 kcal","Protein 21g","Carbohydrate 22g","Total fat 50g"], uses:"Snack straight from the pack, add to breakfast bowls, bake with them or blend into desserts." },
  { id:"cashew-nuts", name:"Cashew Nuts", image:"Images/Cashew_Nuts.jpeg", quantity:"200g", price:300, discount:20, discountedPrice:240, category:"Dry Fruits & Nuts", description:"Versatile cashew nuts for snacking, cooking, sweets and gifting.", ingredients:"Cashew nuts.", nutrition:["Energy 553 kcal","Protein 18g","Carbohydrate 30g","Total fat 44g"], uses:"A creamy, crunchy addition to snack mixes, gravies, sweets and festive trays." },
  { id:"dry-dates", name:"Dry Dates", image:"Images/Dry_Dates.jpeg", quantity:"200g", price:80, discount:15, discountedPrice:68, category:"Dry Fruits & Nuts", description:"Naturally sweet dry dates for traditional recipes, dry-fruit mixes and pantry staples.", ingredients:"Dried dates.", nutrition:["Energy 282 kcal","Protein 2.5g","Carbohydrate 75g","Total fat 0.4g"], uses:"Use for natural sweetness in recipes, enjoy as a snack, or pair with nuts and seeds." },
  { id:"roasted-mix-seed", name:"Roasted Mix Seeds", image:"Images/Mix_Seeds_Roasted.jpeg", quantity:"200g", price:200, discount:20, discountedPrice:160, category:"Seeds", description:"A crunchy roasted seed blend for convenient snacking and topping everyday meals.", ingredients:"Roasted seed blend (pumpkin, sunflower, watermelon and flax seeds).", nutrition:["Energy 559 kcal","Protein 24g","Carbohydrate 20g","Total fat 45g"], uses:"Sprinkle over salads and bowls, add to trail mixes, or enjoy by the handful." },
  { id:"pumpkin-seed", name:"Pumpkin Seeds", image:"Images/Pumpkin_Seeds.jpeg", quantity:"200g", price:200, discount:20, discountedPrice:160, category:"Seeds", description:"Pumpkin seeds for bowls, baking, trail mixes and everyday snacking.", ingredients:"Pumpkin seeds.", nutrition:["Energy 559 kcal","Protein 30g","Carbohydrate 11g","Total fat 49g"], uses:"Top smoothies and salads, fold into baking, or keep nearby for a crunchy snack." },
  { id:"sunflower-seed", name:"Sunflower Seeds", image:"Images/Sunflower_Seeds.jpeg", quantity:"200g", price:150, discount:20, discountedPrice:120, category:"Seeds", description:"Sunflower seeds with a mild nutty crunch for snacks, toppings and pantry recipes.", ingredients:"Sunflower seeds.", nutrition:["Energy 584 kcal","Protein 21g","Carbohydrate 20g","Total fat 51g"], uses:"Use in salads, smoothies, granola, baking or a simple snack mix." },
  { id:"trail-mix", name:"Trail Mix", image:"Images/Trail_Mix.jpeg", quantity:"500g", price:800, discount:20, discountedPrice:640, category:"Trail Mix", description:"A wholesome mix of dry fruits, nuts and seeds for travel, work breaks and active days.", ingredients:"Dry fruits, nuts and seeds. See the pack for the complete ingredient list.", nutrition:["Energy 510 kcal","Protein 15g","Carbohydrate 42g","Total fat 32g"], uses:"A convenient companion for travel, office snack breaks, breakfast bowls and sharing." },
  { id:"pure-cow-ghee", name:"Pure Cow Ghee", image:"Images/Pure_Cow_Ghee.jpeg", quantity:"250g", price:300, discount:10, discountedPrice:270, category:"Ghee", description:"Pure cow ghee for cooking, traditional recipes and everyday pantry essentials.", ingredients:"Pure cow milk fat (ghee).", nutrition:["Energy 897 kcal","Protein 0g","Carbohydrate 0g","Total fat 99.8g"], uses:"Use for cooking, tempering, sweets and traditional home-style meals." }
];

const productVariants = {
  "premium-makhana": [["100g", 150, 200], ["200g", 280, 350],], "americano-almond": [["200g", 240, 300], ["500g", 550, 750]], "cashew-nuts": [["200g", 240, 300], ["500g", 550, 750]], "dry-dates": [["200g", 68, 80], ["500g", 175, 250], ["1kg", 340, 500]], "roasted-mix-seed": [["200g", 160, 200], ["500g", 375, 500]], "pumpkin-seed": [["200g", 160, 200], ["500g", 375, 500]], "sunflower-seed": [["200g", 120, 150], ["500g", 285, 450]], "trail-mix": [["250g", 350, 500], ["500g", 640, 800]], "pure-cow-ghee": [["100g", 140, 200], ["250g", 270, 300], ["500g", 520, 600]]
};
window.HARVEST_PRODUCTS.forEach((product) => { product.variants = productVariants[product.id].map(([quantity, sellingPrice, mrp]) => ({ id: quantity.toLowerCase(), quantity, sellingPrice, mrp })); });
